// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWoEUhpexu-chkRapKVk6-rAVcQipn3G0',
    appId: '1:635450160760:web:8e514e8bd538c7fc229f8d',
    messagingSenderId: '635450160760',
    projectId: 'flutter-caf67',
    authDomain: 'flutter-caf67.firebaseapp.com',
    storageBucket: 'flutter-caf67.appspot.com',
    measurementId: 'G-W1LRMRPQWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkzTglBaluxGyM7O8fsNTXUWKPR-ly1cc',
    appId: '1:635450160760:android:c549dbef799f6aba229f8d',
    messagingSenderId: '635450160760',
    projectId: 'flutter-caf67',
    storageBucket: 'flutter-caf67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX9W-cjXxOQiOvdsqV8q16P7vMhJEM5CA',
    appId: '1:635450160760:ios:77cb04feca1fc6a6229f8d',
    messagingSenderId: '635450160760',
    projectId: 'flutter-caf67',
    storageBucket: 'flutter-caf67.appspot.com',
    iosClientId: '635450160760-a81r4ovvbtt7scgshjqhbta1m1ofql02.apps.googleusercontent.com',
    iosBundleId: 'com.example.voice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX9W-cjXxOQiOvdsqV8q16P7vMhJEM5CA',
    appId: '1:635450160760:ios:77cb04feca1fc6a6229f8d',
    messagingSenderId: '635450160760',
    projectId: 'flutter-caf67',
    storageBucket: 'flutter-caf67.appspot.com',
    iosClientId: '635450160760-a81r4ovvbtt7scgshjqhbta1m1ofql02.apps.googleusercontent.com',
    iosBundleId: 'com.example.voice',
  );
}
